### ISSUE TITLE
能否自定义码率

### ISSUE THREAD

**Issue by Snooker-shoot** [shenbengit/WebRTC-SRS#13]
能否自己设置一个码率，进行推流。capture.startCapture()方法设置的分辨率和帧率，为什么HardwareVideoEncoder中的日志打印出来有很多种分辨率？

**Comment by shenbengit** [comment]
```  java
// 1、
PeerConnection.setBitrate(Integer min, Integer current, Integer max);
// 2、
RtpParameters parameters = RtpSender.getParameters();
List<RtpParameters.Encoding> encodings = parameters.getEncodings();
if (!encodings.isEmpty()) {
    RtpParameters.Encoding encoding = encodings.get(0);
    encoding.maxBitrateBps = maxBitrateBps;
    encoding.minBitrateBps = minBitrateBps;
}
RtpSender.setParameters(parameters);
```
其他方式通过修改sdp；
码率我没有测试过，你可以试一下；
具体打印的是什么日志呢？VideoEncoder 只会编码一种分辨率，多次打印可能是分辨率有变化。

**Comment by Snooker-shoot** [comment]
> 

首先非常感谢您为我解答，我试了您说的第一种方法，三个参数都传的是1000*1000，Android stuido的日志如下
`HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=60, height=1920}
HardwareVideoEncoder: Format: {color-format=21, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=30, height=1920}
`
我想这应该是生效了，但是为什么会有两条日志，并且bitrate是不一样的，分辨率我设置的是1920*1080  帧率是30，只在capture.startCapture()时设置了一次。

您说的第二种方法，我是这样尝试的：
`
 //从PeerConnection获取所有sender
        val senders = peerConnection?.senders
        //遍历每个sender
        senders?.forEach {
            //找到视频的sender
            if (it.track()?.kind() == "video") {
                vSenders = it
            }
        }

        //取出视频sender的参数
        val params = vSenders?.parameters
        //判断参数里面是否有encoding
        if (params?.encodings?.isEmpty() == true) {
            Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空")
            return
        }
        //通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率
        params?.encodings!![0].maxBitrateBps = 1000 * 1000
`
params?.encodings?.isEmpty()这里为空了，所以就没法设置maxBitrateBps了。还望指教。再次感谢您为我解答疑惑，谢谢！

**Comment by Snooker-shoot** [comment]
> ```java
> // 1、
> PeerConnection.setBitrate(Integer min, Integer current, Integer max);
> // 2、
> RtpParameters parameters = RtpSender.getParameters();
> List<RtpParameters.Encoding> encodings = parameters.getEncodings();
> if (!encodings.isEmpty()) {
>     RtpParameters.Encoding encoding = encodings.get(0);
>     encoding.maxBitrateBps = maxBitrateBps;
>     encoding.minBitrateBps = minBitrateBps;
> }
> RtpSender.setParameters(parameters);
> ```
> 
> 其他方式通过修改sdp； 码率我没有测试过，你可以试一下； 具体打印的是什么日志呢？VideoEncoder 只会编码一种分辨率，多次打印可能是分辨率有变化。

首先非常感谢您为我解答，我试了您说的第一种方法，三个参数都传的是1000 x 1000，Android stuido的日志如下
`HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=60, height=1920}

HardwareVideoEncoder: Format: {color-format=21, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=30, height=1920}
`
我想这应该是生效了，但是为什么会有两条日志，并且bitrate是不一样的，分辨率我设置的是1920 x 1080  帧率是30，只在capture.startCapture()时设置了一次。

您说的第二种方法，我是这样尝试的：
`
 //从PeerConnection获取所有sender
        val senders = peerConnection?.senders
        //遍历每个sender
        senders?.forEach {
            //找到视频的sender
            if (it.track()?.kind() == "video") {
                vSenders = it
            }
        }

        //取出视频sender的参数
        val params = vSenders?.parameters
        //判断参数里面是否有encoding
        if (params?.encodings?.isEmpty() == true) {
            Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空")
            return
        }
        //通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率
        params?.encodings!![0].maxBitrateBps = 1000 * 1000
`
params?.encodings?.isEmpty()这里为空了，所以就没法设置maxBitrateBps了。还望指教。再次感谢您为我解答疑惑，谢谢！

**Comment by shenbengit** [comment]
音视频流

> > ```java
> > // 1、
> > PeerConnection.setBitrate(Integer min, Integer current, Integer max);
> > // 2、
> > RtpParameters parameters = RtpSender.getParameters();
> > List<RtpParameters.Encoding> encodings = parameters.getEncodings();
> > if (!encodings.isEmpty()) {
> >     RtpParameters.Encoding encoding = encodings.get(0);
> >     encoding.maxBitrateBps = maxBitrateBps;
> >     encoding.minBitrateBps = minBitrateBps;
> > }
> > RtpSender.setParameters(parameters);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其他方式通过修改sdp； 码率我没有测试过，你可以试一下； 具体打印的是什么日志呢？VideoEncoder 只会编码一种分辨率，多次打印可能是分辨率有变化。
> 
> 首先非常感谢您为我解答，我试了您说的第一种方法，三个参数都传的是1000 x 1000，Android stuido的日志如下 `HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=60, height=1920}
> 
> HardwareVideoEncoder: Format: {color-format=21, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=30, height=1920} ` 我想这应该是生效了，但是为什么会有两条日志，并且bitrate是不一样的，分辨率我设置的是1920 x 1080 帧率是30，只在capture.startCapture()时设置了一次。
> 
> 您说的第二种方法，我是这样尝试的： ` //从PeerConnection获取所有sender val senders = peerConnection?.senders //遍历每个sender senders?.forEach { //找到视频的sender if (it.track()?.kind() == "video") { vSenders = it } }
> 
> ```
>     //取出视频sender的参数
>     val params = vSenders?.parameters
>     //判断参数里面是否有encoding
>     if (params?.encodings?.isEmpty() == true) {
>         Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空")
>         return
>     }
>     //通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率
>     params?.encodings!![0].maxBitrateBps = 1000 * 1000
> ```
> 
> ` params?.encodings?.isEmpty()这里为空了，所以就没法设置maxBitrateBps了。还望指教。再次感谢您为我解答疑惑，谢谢！
1、日志的原因不是很清楚；
2、音视频流你用的peerConnection.addTransceiver()的方式吧，这个方法会返回RtpTransceiver，你用RtpTransceiver.getSender()试试呢。

**Comment by Snooker-shoot** [comment]
> 

再次感谢您为我答疑！！！
我试了RtpTransceiver.getSender()
 videoTrack?.let {
                val rtpTransceiver = addTransceiver(
                    it,
                    RtpTransceiver.RtpTransceiverInit(RtpTransceiver.RtpTransceiverDirection.SEND_ONLY)
                )
                val sender = rtpTransceiver.sender
                //取出视频sender的参数
                val params = sender?.parameters
                //判断参数里面是否有encodings
                if (params?.encodings?.isEmpty() == true) {
                    Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空")
                    return
                }
                //通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率
                params?.encodings!![0].maxBitrateBps = 1000 * 1000

                //将调整好的码率重新设置回sender中，这样设置的码率就起作用了
                sender.parameters = params
            }
依然为空，不知道是不是我写的有问题。

**Comment by Snooker-shoot** [comment]
> 音视频流
> 
> > > ```java
> > > // 1、
> > > PeerConnection.setBitrate(Integer min, Integer current, Integer max);
> > > // 2、
> > > RtpParameters parameters = RtpSender.getParameters();
> > > List<RtpParameters.Encoding> encodings = parameters.getEncodings();
> > > if (!encodings.isEmpty()) {
> > >     RtpParameters.Encoding encoding = encodings.get(0);
> > >     encoding.maxBitrateBps = maxBitrateBps;
> > >     encoding.minBitrateBps = minBitrateBps;
> > > }
> > > RtpSender.setParameters(parameters);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 其他方式通过修改sdp； 码率我没有测试过，你可以试一下； 具体打印的是什么日志呢？VideoEncoder 只会编码一种分辨率，多次打印可能是分辨率有变化。
> > 
> > 
> > 首先非常感谢您为我解答，我试了您说的第一种方法，三个参数都传的是1000 x 1000，Android stuido的日志如下 `HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=60, height=1920}
> > HardwareVideoEncoder: Format: {color-format=21, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=30, height=1920} ` 我想这应该是生效了，但是为什么会有两条日志，并且bitrate是不一样的，分辨率我设置的是1920 x 1080 帧率是30，只在capture.startCapture()时设置了一次。
> > 您说的第二种方法，我是这样尝试的： ` //从PeerConnection获取所有sender val senders = peerConnection?.senders //遍历每个sender senders?.forEach { //找到视频的sender if (it.track()?.kind() == "video") { vSenders = it } }
> > ```
> >     //取出视频sender的参数
> >     val params = vSenders?.parameters
> >     //判断参数里面是否有encoding
> >     if (params?.encodings?.isEmpty() == true) {
> >         Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空")
> >         return
> >     }
> >     //通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率
> >     params?.encodings!![0].maxBitrateBps = 1000 * 1000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ` params?.encodings?.isEmpty()这里为空了，所以就没法设置maxBitrateBps了。还望指教。再次感谢您为我解答疑惑，谢谢！
> > 1、日志的原因不是很清楚；
> > 2、音视频流你用的peerConnection.addTransceiver()的方式吧，这个方法会返回RtpTransceiver，你用RtpTransceiver.getSender()试试呢。

再次感谢您为我答疑！！！
我试了RtpTransceiver.getSender()
videoTrack?.let {
val rtpTransceiver = addTransceiver(
it,
RtpTransceiver.RtpTransceiverInit(RtpTransceiver.RtpTransceiverDirection.SEND_ONLY)
)
val sender = rtpTransceiver.sender
//取出视频sender的参数
val params = sender?.parameters
//判断参数里面是否有encodings
if (params?.encodings?.isEmpty() == true) {
Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空")
return
}
//通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率
params?.encodings!![0].maxBitrateBps = 1000 * 1000

            //将调整好的码率重新设置回sender中，这样设置的码率就起作用了
            sender.parameters = params
        }
依然为空，不知道是不是我写的有问题。

**Comment by shenbengit** [comment]
> > 音视频流
> > > > ```java
> > > > // 1、
> > > > PeerConnection.setBitrate(Integer min, Integer current, Integer max);
> > > > // 2、
> > > > RtpParameters parameters = RtpSender.getParameters();
> > > > List<RtpParameters.Encoding> encodings = parameters.getEncodings();
> > > > if (!encodings.isEmpty()) {
> > > >     RtpParameters.Encoding encoding = encodings.get(0);
> > > >     encoding.maxBitrateBps = maxBitrateBps;
> > > >     encoding.minBitrateBps = minBitrateBps;
> > > > }
> > > > RtpSender.setParameters(parameters);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 其他方式通过修改sdp； 码率我没有测试过，你可以试一下； 具体打印的是什么日志呢？VideoEncoder 只会编码一种分辨率，多次打印可能是分辨率有变化。
> > > 
> > > 
> > > 首先非常感谢您为我解答，我试了您说的第一种方法，三个参数都传的是1000 x 1000，Android stuido的日志如下 `HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=60, height=1920} HardwareVideoEncoder: Format: {color-format=21, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=30, height=1920} ` 我想这应该是生效了，但是为什么会有两条日志，并且bitrate是不一样的，分辨率我设置的是1920 x 1080 帧率是30，只在capture.startCapture()时设置了一次。
> > > 您说的第二种方法，我是这样尝试的： ` //从PeerConnection获取所有sender val senders = peerConnection?.senders //遍历每个sender senders?.forEach { //找到视频的sender if (it.track()?.kind() == "video") { vSenders = it } }
> > > ```
> > >     //取出视频sender的参数
> > >     val params = vSenders?.parameters
> > >     //判断参数里面是否有encoding
> > >     if (params?.encodings?.isEmpty() == true) {
> > >         Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空")
> > >         return
> > >     }
> > >     //通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率
> > >     params?.encodings!![0].maxBitrateBps = 1000 * 1000
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ` params?.encodings?.isEmpty()这里为空了，所以就没法设置maxBitrateBps了。还望指教。再次感谢您为我解答疑惑，谢谢！
> > > 1、日志的原因不是很清楚；
> > > 2、音视频流你用的peerConnection.addTransceiver()的方式吧，这个方法会返回RtpTransceiver，你用RtpTransceiver.getSender()试试呢。
> 
> 再次感谢您为我答疑！！！ 我试了RtpTransceiver.getSender() videoTrack?.let { val rtpTransceiver = addTransceiver( it, RtpTransceiver.RtpTransceiverInit(RtpTransceiver.RtpTransceiverDirection.SEND_ONLY) ) val sender = rtpTransceiver.sender //取出视频sender的参数 val params = sender?.parameters //判断参数里面是否有encodings if (params?.encodings?.isEmpty() == true) { Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空") return } //通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率 params?.encodings!![0].maxBitrateBps = 1000 * 1000
> 
> ```
>         //将调整好的码率重新设置回sender中，这样设置的码率就起作用了
>         sender.parameters = params
>     }
> ```
> 
> 依然为空，不知道是不是我写的有问题。

应该是调用时机的问题，初始化时RtpParameters 没有初始化完成，你在PeerConnection连接状态变成成功时，再调用一次看看呢。void onConnectionChange(PeerConnection.PeerConnectionState newState)，或者setLocalDescription()回调成功之后试试。

**Comment by Snooker-shoot** [comment]
> > > 音视频流
> > > > > ```java
> > > > > // 1、
> > > > > PeerConnection.setBitrate(Integer min, Integer current, Integer max);
> > > > > // 2、
> > > > > RtpParameters parameters = RtpSender.getParameters();
> > > > > List<RtpParameters.Encoding> encodings = parameters.getEncodings();
> > > > > if (!encodings.isEmpty()) {
> > > > >     RtpParameters.Encoding encoding = encodings.get(0);
> > > > >     encoding.maxBitrateBps = maxBitrateBps;
> > > > >     encoding.minBitrateBps = minBitrateBps;
> > > > > }
> > > > > RtpSender.setParameters(parameters);
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 其他方式通过修改sdp； 码率我没有测试过，你可以试一下； 具体打印的是什么日志呢？VideoEncoder 只会编码一种分辨率，多次打印可能是分辨率有变化。
> > > > 
> > > > 
> > > > 首先非常感谢您为我解答，我试了您说的第一种方法，三个参数都传的是1000 x 1000，Android stuido的日志如下 `HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=60, height=1920} HardwareVideoEncoder: Format: {color-format=21, i-frame-interval=20, mime=video/avc, width=1080, bitrate-mode=2, bitrate=968000, frame-rate=30, height=1920} ` 我想这应该是生效了，但是为什么会有两条日志，并且bitrate是不一样的，分辨率我设置的是1920 x 1080 帧率是30，只在capture.startCapture()时设置了一次。
> > > > 您说的第二种方法，我是这样尝试的： ` //从PeerConnection获取所有sender val senders = peerConnection?.senders //遍历每个sender senders?.forEach { //找到视频的sender if (it.track()?.kind() == "video") { vSenders = it } }
> > > > ```
> > > >     //取出视频sender的参数
> > > >     val params = vSenders?.parameters
> > > >     //判断参数里面是否有encoding
> > > >     if (params?.encodings?.isEmpty() == true) {
> > > >         Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空")
> > > >         return
> > > >     }
> > > >     //通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率
> > > >     params?.encodings!![0].maxBitrateBps = 1000 * 1000
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ` params?.encodings?.isEmpty()这里为空了，所以就没法设置maxBitrateBps了。还望指教。再次感谢您为我解答疑惑，谢谢！
> > > > 1、日志的原因不是很清楚；
> > > > 2、音视频流你用的peerConnection.addTransceiver()的方式吧，这个方法会返回RtpTransceiver，你用RtpTransceiver.getSender()试试呢。
> > 
> > 
> > 再次感谢您为我答疑！！！ 我试了RtpTransceiver.getSender() videoTrack?.let { val rtpTransceiver = addTransceiver( it, RtpTransceiver.RtpTransceiverInit(RtpTransceiver.RtpTransceiverDirection.SEND_ONLY) ) val sender = rtpTransceiver.sender //取出视频sender的参数 val params = sender?.parameters //判断参数里面是否有encodings if (params?.encodings?.isEmpty() == true) { Log.d("Snooker -> ", "initPushRTC: parameters?.encodings 为空") return } //通过在 encoding 中的maxBitrate可以限制传输码率，设置传输速率 params?.encodings!![0].maxBitrateBps = 1000 * 1000
> > ```
> >         //将调整好的码率重新设置回sender中，这样设置的码率就起作用了
> >         sender.parameters = params
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 依然为空，不知道是不是我写的有问题。
> 
> 应该是调用时机的问题，初始化时RtpParameters 没有初始化完成，你在PeerConnection连接状态变成成功时，再调用一次看看呢。void onConnectionChange(PeerConnection.PeerConnectionState newState)，或者setLocalDescription()回调成功之后试试。

谢谢，非常感谢，我试了一下，成功了，并且在调用时机正确的情况下使用peerConnection?.senders也可以
