### ISSUE TITLE
视频默认是什么编解码格式，H.264?可以修改吗

### ISSUE THREAD

**Issue by maccSigma** [shenbengit/WebRTC-SRS#14]

**Comment by shenbengit** [comment]
srs 目前只能用h.264，av1格式android目前还用不了，vp8、vp9 srs不支持，所以目前只能用h.264

**Comment by maccSigma** [comment]
> srs 目前只能用h.264，av1格式android目前还用不了，vp8、vp9 srs不支持，所以目前只能用h.264

谢谢，可以设置为硬编码吗？

**Comment by shenbengit** [comment]
默认h264 只支持硬编，但只支持部分编码器，想要扩展的话，看下 https://github.com/shenbengit/WebRTCExtension
