### ISSUE TITLE
依赖添加无效

### ISSUE THREAD

**Issue by Duanzq-GIT** [shenbengit/WebRTC-SRS#2]
大神，我在自己的项目Gradle里添加依赖
implementation ("com.github.shenbengit:MVVMKit:1.0.3")
implementation ("com.github.shenbengit:WebRTCExtension:1.0.1")
想学习一波，但是并没有用，可能是什么原因呀

**Comment by shenbengit** [comment]
我这边依赖没问题，[MVVMKit地址](https://github.com/shenbengit/MVVMKit) ，[WebRTCExtension地址](https://github.com/shenbengit/WebRTCExtension)，都是发布在jitpack上的，用最新版试一下。可能是网络问题。
![image](https://user-images.githubusercontent.com/24364422/145506931-8f50cbfd-5b68-4ea0-8eeb-5448209c229d.png)

**Comment by Duanzq-GIT** [comment]
我在添加了


后，可以了，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shenbengit/WebRTC-SRS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 中午12:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenbengit/WebRTC-SRS] 依赖添加无效 (Issue #2)





 
我这边依赖没问题，MVVMKit地址 ，WebRTCExtension地址，都是发布在jitpack上的，用最新版试一下。可能是网络问题。
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
