### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by aceip** [shenbengit/WebRTC-SRS#5]
您好！工程编译完成后install闪退，
No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in base.apk!classes9.dex)

**Comment by shenbengit** [comment]
这个问题是koin的与kotlin版本不兼容的bug，把Level.DEBUG改成Level.ERROR即可。
![O71%UBI7 0R8%4V)WQ~A5 Y](https://user-images.githubusercontent.com/24364422/170985809-690bf5bc-3f21-4167-a3bd-8b9b83c2925c.png)
。
