### ISSUE TITLE
请问onAddStream、onAddTrack都收不到视频流的原因一般是什么呢?

### ISSUE THREAD

**Issue by TangStudio** [shenbengit/WebRTC-SRS#6]
我们后端自己搭了个p2p，安卓端只需要拉流就行了，服务端用addTrack和addStream不断往安卓端推流，但是我安卓端这边onAddStream、onAddTrack却怎么都无法走这2个回调，是基于你的PULL工程基础上改的。方便的话能加QQ或者开github的讨论吗，感谢大佬。

**Comment by shenbengit** [comment]
1、我的demo使用是否正常？
2、不回调可能是sdp设置错误导致；
3、如果demo正常，仔细检查下代码。

**Comment by TangStudio** [comment]
我们是web端推流，android端拉流，在sdp设置上有什么需要注意的吗

**Comment by shenbengit** [comment]
demo正常吗？看我那篇拉流那篇的博客，里面有具体的流程。
