### ISSUE TITLE
点击“推流”按钮能正常推流，但无法播放，预览界面显示黑屏

### ISSUE THREAD

**Issue by 1241328428** [shenbengit/WebRTC-SRS#8]
附上图片如下，请问是什么原因导致的呢
![image](https://user-images.githubusercontent.com/12364599/190562133-ec1bada4-3f09-4af0-a6e5-7ff78563c898.png)
![image](https://user-images.githubusercontent.com/12364599/190562632-ec29e837-ba62-497e-a880-4dcd1821c357.png)
![image](https://user-images.githubusercontent.com/12364599/190562905-3a12d654-b29e-4624-a375-afa3445353d5.png)

**Comment by shenbengit** [comment]
![image](https://user-images.githubusercontent.com/24364422/190563416-cdaa541e-4045-428e-84c7-ef0cddbbdbc8.png)
srs未设置candidate

**Comment by 1241328428** [comment]
我试了下改candidate，offer的sdp也不会变哦，candidate影响的应该是接口返回answer的sdp吧？
![image](https://user-images.githubusercontent.com/12364599/190566285-2ded2a33-fcbd-4d3e-9260-a24a8a526fc2.png)

![image](https://user-images.githubusercontent.com/12364599/190565616-cfdde738-8d2f-4123-bf49-312020ef3a9e.png)

**Comment by shenbengit** [comment]
看错了。。。srs的网页demo也不行吗？

**Comment by shenbengit** [comment]
应该是你这个推流地址的问题，不要用localhost试试。

**Comment by 1241328428** [comment]
解决了，日了狗了，是APP的设置权限问题，权限没打开，打开就可以了
